# Generated by Django 2.0.2 on 2019-01-28 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A short sentence about the product', max_length=50)),
                ('introduction', models.TextField(default='An introduction about the product')),
                ('product_link', models.CharField(default='Http://', max_length=50)),
                ('product_icon', models.ImageField(default='default_icon.png', upload_to='images')),
                ('image', models.ImageField(default='default_image.png', upload_to='images')),
                ('votes', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
